### ISSUE TITLE
Add support for encrypted variables

### ISSUE THREAD

**Issue by GustavoKatel** [GustavoKatel/alfredcmd#5]
With that users would be able to define encrypted variables inside the `alfred.toml`. So it would be able to expose their config file without exposing sensitive information.

This is similar to how passwords are handled in `.travis.yml` files

Suggested example:

```toml
[variables]
custom_token="ENCRYPTED_CONTENT"
```
